import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "@styles/globals.css"
import "@fortawesome/fontawesome-svg-core/styles.css";
import 'react-quill/dist/quill.snow.css';
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import AuthProvider from '@components/AuthProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
